spring:
  application:
    name: PostService
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmqPost
    password: rabbitmqPost@!#
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongoDbPost 