spring:
  application:
    name: PostService
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmqPost
    password: rabbitmqPost@!#
  data:
    mongodb:
      uri: mongodb://algapost:algapost!%40%23100@localhost:27017/mongoDbPost?authSource=admin
     # host:  workspace_algapost-mongoDbPost-1
     # port: 27017
     # username: algapost
     # password: algapost!@#100
     # database: mongoDbPost 